### ISSUE TITLE
提交疑问

### ISSUE THREAD

**Issue by xigua0331** [maoabc/nmmp#10]
我加固成功后，fastjson不能使用了，因此json字符串转化不成对象，所有的网络请求都不能用了。我想能不能通过ProguardMappingConfig的keepClass方法来处理？

**Comment by maoabc** [comment]
可以啊，直接判断字符串，fastjson包名开头的返回true就行。

**Comment by xigua0331** [comment]
JNI DETECTED ERROR IN APPLICATION: use of invalid jobject 0x7f9f770500
