### ISSUE TITLE
我使用nmmp加固xposed模块在lsposed环境下运行时遇到了如下错误

### ISSUE THREAD

**Issue by xiaotujinbnb** [maoabc/nmmp#109]

**Comment by maoabc** [comment]
xposed相关框架不支持加载本地库吧，不然就是实现有问题。

**Comment by xiaotujinbnb** [comment]
是不支持但是我看了一下np管理器使用的vmp看着是使用的你这个他java也是直接load的so就可以加载成功

**Comment by maoabc** [comment]
应该需要改so加载位置什么的，或者启动时hook了so加载相关函数。我都是按正常情况给apk或者aab用，没考虑过这些框架所以不清楚。

**Comment by xiaotujinbnb** [comment]
我对比了一下安装包看不出来有区别 有没有考虑适配框架呢

**Comment by xiaotujinbnb** [comment]
我在研究研究吧

**Comment by maoabc** [comment]
没必要，从来不用那些，刷机折腾那些浪费时间。

**Comment by fengchenf** [comment]
应该可以吧,一些xposed模块都用了Umeng统计,那个需要加载so,用着也都没出现过问题. 应该是实现有问题.

**Comment by xiaotujinbnb** [comment]
> 应该可以吧，一些xposed模块都用了Umeng统计，那个需要加载so，用着也没出现过问题。但应实现此问题。

已经解决了

**Comment by xjgithub321** [comment]
@xiaotujinbnb 你好你是报了找不到so的异常吗，请问下你是怎么解决的啊
