### ISSUE TITLE
Mac 报错：No such file or directory

### ISSUE THREAD

**Issue by ffdsss** [maoabc/nmmp#110]
佬，已经修改了mac的sdk ndk路径，运行最后一步提示No such file or directory
![image](https://github.com/maoabc/nmmp/assets/48895716/906b046c-e1fd-4b47-a636-4290e5ba6ea0)
![image](https://github.com/maoabc/nmmp/assets/48895716/ff4d35fc-92d8-4cd8-9aa5-3f09f5a3ccf9)

**Comment by maoabc** [comment]
去看你那版本的ndk目录结构，自己改。不同版本ndk目录有差异，自己适配就行了

**Comment by maoabc** [comment]
你是ndk21，项目里目录应该是按ndk25以上

XIel ***@***.***> 于 2024年4月23日周二 22:35写道：

**Comment by maoabc** [comment]
好吧，跟邮件看混了。你找下ndk21的strip在哪，然后修改一下路径，项目里的ndk版本好像是按25以上适配的，ndk相关命令路径跟执行都在BuildNtiveLib这个类里，配置文件无法满足可以直接修改它

**Comment by ffdsss** [comment]
没事了 我给这写死了 
![image](https://github.com/maoabc/nmmp/assets/48895716/0b0b099e-9a44-462b-9ed1-2490eef9fbec)
