### ISSUE TITLE
加固后在Android11上安装后打开报错 java.lang.NoSuchMethodError: toWindowInsetsCompat

### ISSUE THREAD

**Issue by ffdsss** [maoabc/nmmp#115]
已经在代码中忽略了androidx

![image](https://github.com/maoabc/nmmp/assets/48895716/d739617d-16b4-413f-bdc5-29721d92a669)

![image](https://github.com/maoabc/nmmp/assets/48895716/58374d1e-a22a-4329-b570-1db074008619)
![image](https://github.com/maoabc/nmmp/assets/48895716/45edc03b-70a8-4c0e-965c-e4fe3807503e)

**Comment by maoabc** [comment]
仔细看代码跟说明，zipCopy是复制apk文件的，你改这里没任何作用。规则文件你需要自己建立个txt里面写规则，然后处理dex时才生效。如果你需要实现自己的过滤格式，看ClassAndMethodFilter接口。

**Comment by ffdsss** [comment]
> 仔细看代码跟说明，zipCopy是复制apk文件的，你改这里没任何作用。规则文件你需要自己建立个txt里面写规则，然后处理dex时才生效。如果你需要实现自己的过滤格式，看ClassAndMethodFilter接口。

我只需跳过加固androidx，应该修改哪个类

**Comment by ffdsss** [comment]
> 仔细看代码跟说明，zipCopy是复制apk文件的，你改这里没任何作用。规则文件你需要自己建立个txt里面写规则，然后处理dex时才生效。如果你需要实现自己的过滤格式，看ClassAndMethodFilter接口。

感谢大佬回复。   修改了BasicKeepConfig类中的相关规则可以正常运行了
