### ISSUE TITLE
作者，您好请问安装demo中的app-release-protect.apk报packageinfo is null是什么情况

### ISSUE THREAD

**Issue by chuanye1993** [maoabc/nmmp#118]
小米11pro机型。
用这个项目加固，是不是混淆就没什么必要了？

**Comment by chuanye1993** [comment]
我自己加固apk签名后安装也是报这个错误

**Comment by maoabc** [comment]
混淆后再部分重要逻辑使用虚拟化，别全局使用，对性能影响很大。测试的apk没签名。安装出问题一般都是打包问题，如果以前apk没有.so，需要解决.so打包问题。具体可以看安卓6.0关于本地库的相关文档。

**Comment by chuanye1993** [comment]
> 混淆后再部分重要逻辑使用虚拟化，别全局使用，对性能影响很大。测试的apk没签名。安装出问题一般都是打包问题，如果以前apk没有.so，需要解决.so打包问题。具体可以看安卓6.0关于本地库的相关文档。
代码还没有混淆。使用您这个程序之前，原始的apk是可以安装的，但是加固之后签名了也安装不了，没有使用使用zipalign对齐（文档说不需要对齐）

**Comment by maoabc** [comment]
那个demo老版本加固的需要对齐，后来更新把zip处理换成zipflinger后，打包时顺手处理apk对齐问题，就不需要执行额外的对齐命令。

**Comment by chuanye1993** [comment]
> 那个demo老版本加固的需要对齐，后来更新把zip处理换成zipflinger后，打包时顺手处理apk对齐问题，就不需要执行额外的对齐命令。

以前的apk有.so，用的 ndk {abiFilters 'arm64-v8a' }过滤，这会影响到吗？没有混淆，运行的./gradlew assembleRelease签名
并打包。
convertRules.txt 里面，只写了一句：class com.xxxx.xxxxx* { *; }（项目包名路径）
然后加固后再签名就无法安装了

**Comment by maoabc** [comment]
忽略androidx，可能类加载问题会导致native代码在.so加载前运行从而报错，

**Comment by chuanye1993** [comment]
已解决，谢谢作者
