### ISSUE TITLE
不支持64位？

### ISSUE THREAD

**Issue by amimo** [maoabc/nmmp#2]
看解释器貌似不支持64位？
另外想问下大佬，你局部引用溢出怎么处理的。

**Comment by maoabc** [comment]
支持啊，只是之前准备在32位时想把寄存器也换成32位，不过实现起来发现不少问题，就没去兼容。没优化32位，问题也不算大，稍微多占点内存。
给寄存器加个标志，修改寄存器的时候判断之前的寄存器里引用是否为对象，是对象的话就删除引用。新的值如果是对象直接使用NewLocalRef，具体可以看OP_MOVE_OBJECT这条字节码实现

**Comment by amimo** [comment]
了解，我看你使用的dalvik的解释器，以为不支持。
