### ISSUE TITLE
或许可以靠注释来自定义保护的类?

### ISSUE THREAD

**Issue by h45251880** [maoabc/nmmp#4]

**Comment by maoabc** [comment]
这需要在开发时就做，没法对开发后的apk，可能需要类似proguard那种配置文件。目前只实现了读取mapping文件还原混淆后的类名和方法名，然后再判断是否需要保护，不过没想好怎么定义规则文件。

**Comment by h45251880** [comment]
> 这需要在开发时就做，没法对开发后的apk，可能需要类似proguard那种配置文件。目前只实现了读取mapping文件还原混淆后的类名和方法名，然后再判断是否需要保护，不过没想好怎么定义规则文件。

开发后注释好象是能靠逆向smali来达成的 就是先创造 就是先创造一个某dex2c包 内容为
.class public interface abstract annotation Lcom/test/TestDCC/Dex2C;
.super Ljava/lang/Object;
.source "Dex2C.java"

# interfaces
.implements Ljava/lang/annotation/Annotation;


# annotations
.annotation runtime Ljava/lang/annotation/Retention;
    value = .enum Ljava/lang/annotation/RetentionPolicy;->RUNTIME:Ljava/lang/annotation/RetentionPolicy;
.end annotation

然后在要保护的方法名下注释
 .annotation runtime Lcom/protecter/gg/Dex2c;
  .end annotation

只是搞起来真他娘麻烦

**Comment by githubXiaowangzi** [comment]
配置文件就好了，都已经是成品apk了，还搞什么注解
![Screenshot_20210425-203357](https://user-images.githubusercontent.com/44804693/119833485-bc657300-bf31-11eb-94db-28182e69ce80.png)

**Comment by githubXiaowangzi** [comment]
配置文件就好了，都已经是成品apk了，还搞什么注解
![Uploading IMG_20210527_212219.jpg…]()

**Comment by h45251880** [comment]
> 配置文件就好了，都已经是成品apk了，还搞什么注解
> ![IMG_20210527_212219](https://user-images.githubusercontent.com/44804693/119834204-53cac600-bf32-11eb-958d-eaa6a472ae80.jpg)

Dex-vmp跟你里面的东西完全不一样甚至里面都没有 不要以为NP万万都能 而且注释主要是搞自定义要保护的方法名或类

**Comment by h45251880** [comment]
> 配置文件就好了，都已经是成品apk了，还搞什么注解
> ![IMG_20210527_212219](https://user-images.githubusercontent.com/44804693/119834204-53cac600-bf32-11eb-958d-eaa6a472ae80.jpg)

只是个建议而已

**Comment by maoabc** [comment]
注解没必要，都处理dex了还管它注解不注解，按照配置文件的规则对类名和方法名进行保护这样比较好。注解在开发时用差不多，然后处理dex时读取注解再处理，但对开发好的apk没用处。

**Comment by h45251880** [comment]
> 注解没必要，都处理dex了还管它注解不注解，按照配置文件的规则对类名和方法名进行保护这样比较好。注解在开发时用差不多，然后处理dex时读取注解再处理，但对开发好的apk没用处。

OKOK

**Comment by Krosxx** [comment]
类和方法注解 有些需求，在使用R8混淆 有些类会消失 mapping还原不到，函数就会漏掉
