### ISSUE TITLE
java8  win11

### ISSUE THREAD

**Issue by zhaoyao1019** [maoabc/nmmp#49]
is:issue is:open C:\Users\tucker\nmmp\nmm-protect>gradlew.bat build  FAILURE: Build failed with an exception.  * Where: Build file 'C:\Users\tucker\nmmp\nmm-protect\build.gradle' line: 20  * What went wrong: Could not determine the dependencies of task ':jar'. > Could not resolve all files for configuration ':runtimeClasspath'.    > Could not resolve project :apkprotect.      Required by:          project :       > No matching variant of project :apkprotect was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its dependencies declared externally but:           - Variant 'apiElements' capability nmm-protect:apkprotect:unspecified declares a library, packaged as a jar, and its dependencies declared externally:               - Incompatible because this component declares an API of a component compatible with Java 9 and the consumer needed a runtime of a component compatible with Java 8           - Variant 'runtimeElements' capability nmm-protect:apkprotect:unspecified declares a runtime of a library, packaged as a jar, and its dependencies declared externally:               - Incompatible because this component declares a component compatible with Java 9 and the consumer needed a component compatible with Java 8  * Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.  * Get more help at https://help.gradle.org

**Comment by maoabc** [comment]
最低jdk9
