### ISSUE TITLE
fatal error: 'fficonfig.h' file not found

### ISSUE THREAD

**Issue by ghost** [maoabc/nmmp#52]
I'm trying to compile nmmvm but it depends on jna-android, I can't compile to due missing fficonfig.h. Can you add that file?

![image](https://user-images.githubusercontent.com/111238729/208630345-3bae4eeb-bd4c-4fb3-b5bf-5c2e6bd2f14f.png)

**Comment by maoabc** [comment]
Maybe there is something wrong with your build system, this file is in libffi/src/aarch64/fficonfig.h

**Comment by maoabc** [comment]
Ignored by .gitignore, the fficonfig.h file has been added.
