### ISSUE TITLE
Jar 包中 vmsrc.zip 未更新

### ISSUE THREAD

**Issue by shawnbc** [maoabc/nmmp#60]
按照最新代码编译或者直接下载 release 包，发现 Jar 包中的 vmsrc.zip 还是旧的，没更新。
可以打包替换下最新的 vmsrc.zip

**Comment by maoabc** [comment]
好像忘了，下次改改放源码方式，不然不好用git跟踪文件。

shawnbc ***@***.***> 于 2023年2月2日周四 20:57写道：
