### ISSUE TITLE
args[1]  这个参数传的是什么文件 

### ISSUE THREAD

**Issue by zhuhao666** [maoabc/nmmp#7]
怎么才能过滤不需要保护的类或方法

**Comment by zhuhao666** [comment]
懂了...

**Comment by maoabc** [comment]
这个是proguard的mapping.txt文件，因为没实现根据配置保留class，所以这个暂时没用。可以自己调用，然后代码里写保留规则

**Comment by maoabc** [comment]
想法是根据mapping文件得到混淆前的class名和方法名，然后使用一些规则对保留需要的class。
