### ISSUE TITLE
编译错误：NoSuchFileException

### ISSUE THREAD

**Issue by wangym1551** [maoabc/nmmp#74]
在nmm-protect目录下执行 ./gradlew build 编译时报错

java.nio.file.NoSuchFileException: /home/mao/adbi/TestNative.class
java.io.FileNotFoundException: /home/mao/nmmp/classes2.dex (No such file or directory)

<img width="1544" alt="image" src="https://user-images.githubusercontent.com/11502095/231197968-a62f84b0-61fd-4cd5-bd6f-9aa09b0aed35.png">

我没有mao这个用户，找不到文件也正常，但是不知道为什么会固定这个路径

**Comment by maoabc** [comment]
注释掉测试代码，这是我本地的测试代码。当时懒得加进来，用了本地的文件路径。

**Comment by maoabc** [comment]
那些测试代码里一些固定路径，是我开发时方便观察生成的一些中间文件。把文件生成在顺手的位置，方便查看生成的.dex，.class是否有问题，开源后那些代码没删干净，刚才已经清楚了

**Comment by wangym1551** [comment]
谢谢🙏
