### ISSUE TITLE
axml修改问题

### ISSUE THREAD

**Issue by SharkFall** [maoabc/nmmp#75]
请教一下，大佬

我将AxmlEdit中原本为
final int name = getOrAddString(stringPoolChunk, "name");
改为了
final int name = getOrAddString(stringPoolChunk, "appComponentFactory");
意图是为了修改applciation中的appComponentFactory，但是出了一些问题。

当被修改的axml中已经有appComponentFactory标签时，可以直接修改成功，
而当不含有appComponentFactory标签时，修改后的axml反编译看不到appComponentFactory字段，但是在字符串常量池中时可以看到添加的内容的，麻烦老哥解个惑

**Comment by maoabc** [comment]
好像跟属性顺序有关，安卓系统不按属性名解析，按属性索引什么的。

**Comment by SharkFall** [comment]
> 好像跟属性顺序有关，安卓系统不按属性名解析，按属性索引什么的。

感谢老哥，我再研究下

**Comment by Sheikins** [comment]
@SharkFall 您好，请问您有什么不愉快的事情需要沟通吗？我希望能和你聊天
