### ISSUE TITLE
Build projects的问题

### ISSUE THREAD

**Issue by LoveDoLove** [maoabc/nmmp#76]
我没改任何东西直接run projects
但是run完了过后没有任何出错，为什么没有看到build/lib的folder的
哪里可以找到fatjar😥😥😥

**Comment by maoabc** [comment]
先子模块build，然后gradle build，应该就没问题，更新后生成的jar文件名为vm-protect-{日期}.jar。如果有测试错误可以暂时注释掉它们，不少测试需要依赖文件路径，不同系统下可能有问题。

**Comment by maoabc** [comment]
BuildNativeLib.java里面可以自己修改本地库名称

**Comment by maoabc** [comment]
两个库名称，应该只实现其中libnmmp.so替换，具体实现就是在writeCmakeFile里，vm的cmake文件替换没实现，你可以自己修改vmsrc.zip里cmake文件或者仿造writeCmakeFile实现一个vm下cmake文件的替换。
