### ISSUE TITLE
提交一个App测试，某个类编译so失败的异常反馈，测试App在链接里

### ISSUE THREAD

**Issue by githubXiaowangzi** [maoabc/nmmp#8]
测试app下载：https://wwi.lanzoui.com/irwNzpq7sqh
测试类 tbs.app 
只处理某一个方法是正常的
单独处理这整个类会编译失败，如下图所示，
![image](https://user-images.githubusercontent.com/44804693/120525501-c0e6cb80-c40a-11eb-986c-c7ecca259a94.png)

**Comment by githubXiaowangzi** [comment]
目测是这个类有特殊字符名称的方法名导致的编译失败

**Comment by maoabc** [comment]
嗯，处理方法名时只处理低字节导致的，我测试下，等下提交修复后的

**Comment by githubXiaowangzi** [comment]
正常了
