### ISSUE TITLE
第一次，先对aar混淆，然后再加固。第二次不混淆，加固后，运行app报错。

### ISSUE THREAD

**Issue by yijiepifu** [maoabc/nmmp#89]
CheckJNI: method to register "llllIl" not in the given class. This is slow, consider changing your RegisterNatives calls.
其中“llllIl”是混淆后的方法名，但是我第二次都没有混淆了，为什么还有这个错误提示呢？

**Comment by yijiepifu** [comment]
看起来好像是有缓存

**Comment by yijiepifu** [comment]
![image](https://github.com/maoabc/nmmp/assets/8278902/adea7b55-eab4-41e4-a649-14c97673702a)
如图

**Comment by maoabc** [comment]
不清楚是不是dx过程中一些方法被内联了

**Comment by maoabc** [comment]
可以试着对比一下转换前的jar里面.class文件跟转换后的.dex里的class。如果缓存问题，可以先试着删除上一次生成的所有目录。

**Comment by maoabc** [comment]
windows下之前有遇到文件删除不了的情况，找不到原因，如果你是windows下操作可能得注意这种情况。

**Comment by yijiepifu** [comment]
> windows下之前有遇到文件删除不了的情况，找不到原因，如果你是windows下操作可能得注意这种情况。

貌似是android studio缓存的问题，我是打包aar，先“clean”，然后“assembleRelease”就好了，如果有人遇到可以这样试试，我已经解决了，最后感谢作者的回复
